services:
  postgres:
    image: postgres:16
    container_name: financeai-postgres
    environment:
      POSTGRES_DB: financeai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - financeai_pgdata:/var/lib/postgresql/data

volumes:
  financeai_pgdata: