spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/financeai
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
logging.level.org.springframework.security=DEBUG

# Clave secreta utilizada para firmar los JWT
jwt.secret=EstaEsUnaClaveSecretaDePruebaParaElHackathon
# Duración del token:
# 2 horas
jwt.expiration=7200000
